### ISSUE TITLE
Rundeck + Ansible always send --limit to playbooks

### ISSUE THREAD

**Issue by javierurien** [rundeck-plugins/ansible-plugin#102]
I have a playbook that looks like this:
```
- hosts: localhost
  vars:
    some_var: 'some value' 
  tasks:
    - name: some local task
      set_fact:
        some_local_var: 'some local value'
- hosts: linux
  tasks:
    - name: some linux task
      shell: 'uname -a'
- hosts: windows
  tasks:
    - name: some windows task
      raw: 'ping 127.0.0.1'
```

I run it from command line with:
`# ansible-playbook some_playbook.yml`
And works as expected.

But I cant find a way to run it from rundeck with ansible plugin. (rundeck shell command works)

What I see is that rundeck runs ansible-playbook with the --limit option always and this playbook needs to be run as shown.

My questions are:
Am I writing bad playbooks?
Is there a way to run ansible playbooks without sending a --limit option?

Thanks
