### ISSUE TITLE
Only first ssh user used in multiple plays of one playbook

### ISSUE THREAD

**Issue by shoelzle** [rundeck-plugins/ansible-plugin#141]
# Problem description

Hello,

I have a playbook which consists of two play on different hosts, it looks something like this:
```
---

- name: play 1
  remote_user: user1
  hosts: host1
  roles:
    - role1
  tags: play1

- name: play 2
  remote_user: user2
  hosts: host2
  tasks:
    - debug: msg='asdf'
  tags: play2
```

The playbook is executed in rundeck job which consists of two "Ansible Playbook" workflow steps.
Both steps run the above listed playbook, but with different ansible tags and ssh users:
* Workflow step 1:
** Extra Ansible arguments: --tags=play1
** SSH User: user1
* Workflow step 2:
** Extra Ansible arguments: --tags=play2
** SSH User: user2

With this job I expect the job to use user1 for play1 and user2 for play2.

However, when I execute the job, user1 is used for both workflow steps.

If I separate the two plays into two playbooks, it works as expected.

# Version/Environment

Rundeck: 2.9.2
Ansible Plugin for Rundeck: 2.0.2
Ansible: 2.3.2
Python: 2.7.3
Java: 1.8.0_121

**Comment by DerekTBrown** [comment]
Can you post the output of the log on verbose?

**Comment by shoelzle** [comment]
Playbook:
```
---

- name: play 1
  remote_user: valid_user
  hosts: vm.local
  tasks:
    - debug: msg='aaaa'
  tags: play1

- name: play 2
  remote_user: invalid_user
  hosts: vm.local
  tasks:
    - debug: msg='bbbb'
  tags: play2
```

Runeck-Job definition:
```
- description: ''
  executionEnabled: true
  loglevel: INFO
  name: rundeck-ansible-plugin_issues_141
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: 1
    filter: vm.local
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-become: 'false'
        ansible-extra-param: --tags=play1
        ansible-playbook: /home/valid_user/repos/ansible/playbooks/task_misc/rundeck-ansible-plugin_issue141.yml
        ansible-ssh-auth-type: privateKey
        ansible-ssh-user: valid_user
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    - configuration:
        ansible-become: 'false'
        ansible-extra-param: --tags=play2
        ansible-playbook: /home/valid_user/repos/ansible/playbooks/task_misc/rundeck-ansible-plugin_issue141.yml
        ansible-ssh-auth-type: privateKey
        ansible-ssh-user: invalid_user
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: node-first
```

Please note that rundeck server (vm.local) runs with user "valid_user" in the given setup and the host in the plays is the rundeck server itself.

Debug-Log: [rundeck-ansible-plugin_issue141_debug.zip](https://github.com/Batix/rundeck-ansible-plugin/files/1302128/rundeck-ansible-plugin_issue141_debug.zip)
