### ISSUE TITLE
Do not run playbook when node filter empty

### ISSUE THREAD

**Issue by pawadski** [rundeck-plugins/ansible-plugin#151]
**My Rundeck detail**

* Rundeck version: 2.8.4-1
* install type: (rpm,deb,war,launcher?) RPM 
* OS Name/version: CentOS Linux release 7.3.1611 (Core)
* DB Type/version: mysql? postgres? h2?.. MySQL

**Expected Behavior**

When no nodes are selected by filter ie. it is empty, I'd like the job to not execute.

**Actual Behavior**

When no nodes are selected by filter, job execution runs playbook against all nodes. Is this a problem with "hosts: all" in the playbook itself? A warning is present: "Warning: The Node filters specified for this Job do not match any nodes, execution may fail." but it runs on all nodes anyway.

If this is a problem with the playbook, how do I correct this problem without workarounds like environment variables?

**How to reproduce Behavior**

1. Create a simple playbook
2. Create job with said playbook (yaml details below)
3. Run job without selecting any nodes
4. Go to the log section

**job details:**

```
- description: Testing
  executionEnabled: true
  group: '*'
  id: f8fe978e-8393-4c14-baaf-b3b084ec72c8
  loglevel: INFO
  name: TestPlaybook
  nodeFilterEditable: true
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankOrder: ascending
      threadcount: 2
    filter: 'name: NONE'
  nodesSelectedByDefault: false
  scheduleEnabled: false
  sequence:
    commands:
    - configuration:
        ansible-become: 'false'
        ansible-playbook: /var/lib/jenkins/workspace/DevOps-Repo/playbooks/Empty.yaml
        ansible-ssh-auth-type: privateKey
        ansible-ssh-timeout: '10'
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: parallel
  uuid: f8fe978e-8393-4c14-baaf-b3b084ec72c8
```

**playbook details:**

```
---
- hosts: all
  gather_facts: False
  tasks:
  - name: Message
    debug: msg=asd
```

How would you go about setting this up?
