### ISSUE TITLE
Node not imported from dynamic inventory...

### ISSUE THREAD

**Issue by flynn1973** [rundeck-plugins/ansible-plugin#193]
i can not see the nodes from dynamic inventory in rundeck or while creating a job. only the host where rundack runs show up in the search filter.

the inventory script works perfectly on the command line..

````
root@lpgaixmgmtlx01:/etc/ansible>/etc/ansible/dyninv/inventory.py --list
{
  "_meta": {
    "hostvars": {
      "172.17.14.13": {
        "inventory_hostname": "AIXTEST01"
      }
    }
  },
  "ungrouped": [
    "172.17.14.13"
  ]
}
root@lpgaixmgmtlx01:/etc/ansible>/etc/ansible/dyninv/inventory.py --list
{
  "_meta": {
    "hostvars": {
      "172.17.14.13": {
        "inventory_hostname": "AIXTEST01"
      }
    }
  },
  "ungrouped": [
    "172.17.14.13"
  ]
}
````

project configuration file:
````
#Tue Jul 24 10:16:45 CEST 2018
#edit below
project.ansible-executable=/bin/sh
project.description=run aix playbooks
project.disable.executions=false
project.disable.schedule=false
project.jobs.gui.groupExpandLevel=1
project.label=Ansibe_AIX
project.name=Ansibe_AIX
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.resources.source.2.config.ansible-inventory=/etc/ansible/dyninv/inventory.py --list
project.ssh-authentication=privateKey
project.ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
resources.source.1.config.file=/var/rundeck/projects/Ansibe_AIX/etc/resources.xml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=false
resources.source.1.config.writeable=false
resources.source.1.type=file
resources.source.2.config.ansible-become=false
resources.source.2.config.ansible-config-file-path=/etc/ansible/ansible.cfg
resources.source.2.config.ansible-disable-limit=false
resources.source.2.config.ansible-gather-facts=true
resources.source.2.config.ansible-ignore-errors=true
resources.source.2.type=com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory
service.FileCopier.default.provider=com.batix.rundeck.plugins.AnsibleFileCopier
service.NodeExecutor.default.provider=com.batix.rundeck.plugins.AnsibleNodeExecutor
````
````
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 74f3b1c8-4650-49fe-baea-2049b4e35338
  loglevel: INFO
  name: run_playbook
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ''
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-base-dir-path: /etc/ansible
        ansible-become: 'false'
        ansible-disable-limit: 'false'
        ansible-playbook: /etc/ansible/aix/testplay.yml
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: node-first
  uuid: 74f3b1c8-4650-49fe-baea-2049b4e35338
````
