### ISSUE TITLE
Passing node property values to an Ansible playbook

### ISSUE THREAD

**Issue by karolbe** [rundeck-plugins/ansible-plugin#214]
I have Rundeck configured with EC2 plugin, this way I can retrieve all my EC2 instances and define jobs that run commands on those instances.
This works fine for usual scripting, now I wanted to use Ansible to e.g. start/stop instances. For that to work I need to pass at least EC2 region and instance ID. I have this information in the Rundeck node but I don't know how to pass it to the Ansible playbook, precisely I don't know how to define a variable that will be evaluated to the instanceId value.

This is my playbook:

```
---
- name: Start  instances
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Start the feature instances
      ec2:
        instance_ids: '{{ instanceId }}'
        region: '{{ region }}'
        state: running
        wait: True
```

I tried to define extra variables in different ways but nothing seems to work.

```
{
  "region": "eu-center-1",
  "instanceId":  "{{ node.instanceId }}",
}
``` 

I am using Rundeck 3.0.8 with the Ansible plugin 2.5.0
