### ISSUE TITLE
ssh-agent forwarding

### ISSUE THREAD

**Issue by via-justa** [rundeck-plugins/ansible-plugin#269]
Does the ssh-agent option added in v3.1.0 only allow to add key from agent locally or can it be used to FW the agent to remote host?

If it does not, is there other way to FW the used key to the remote host? 

My use case is that I need the ssh key on the remote host for several task done by ansible but the key should not be stored on the host

**Comment by mcassaniti** [comment]
I didn't even know we added automatic setup of an SSH agent recently. My understanding is that the SSH agent operates the same as it would without Rundeck. The environment variable `SSH_AUTH_SOCK` is set which Ansible can then make use of. I believe Ansible will always try to forward any SSH keys that are loaded in the agent, and obviously the keys are not sent directly to remote hosts.

I've used Ansible with an SSH agent to perform logins to remote hosts without an issue, and even got it to perform an SSH proxy connection with agent based authentication (see [ProxyCommand](https://man.openbsd.org/ssh_config#ProxyCommand) ).

My suggestion would be to test in your environment and report your results for other users. Feel free to close once done.

**Comment by via-justa** [comment]
Hey @mcassaniti thanks for your comment.
On the same node that run Rundeck I can do the ssh-agent forwarding from command line (ansible ad-hoc command) without any issue. 

Playing around with it a bit more, I can say it's really not reliable. I'm running the same task against the same node and it's failing 6/10 runs. I'm not sure if it's because the agent is not ready yet when the command starts, I'm doing something wrong or I got infra issues.
Example job:
```- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: ops/testing jobs
  id: c336e728-96d7-481b-a5d5-b230993e5c0f
  loglevel: INFO
  name: test-job
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: <single host>
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-base-dir-path: /var/rundeck/projects/<project>/ansible_playbooks
        ansible-become: 'false'
        ansible-playbook-inline: |-
          - hosts: all
            tasks:
            - shell: ssh-add -l
        ansible-ssh-auth-type: privateKey
        ansible-ssh-key-storage-path: keys/<key>
        ansible-ssh-passphrase-option: option.password
        ansible-ssh-use-agent: 'true'
        ansible-ssh-user: root
      nodeStep: true
      type: com.batix.rundeck.plugins.AnsiblePlaybookInlineWorkflowNodeStep
    keepgoing: false
    strategy: node-first
  uuid: c336e728-96d7-481b-a5d5-b230993e5c0f
```

The job is just listing the agent keys on the remote host to see that the agent was forwarded.
Am I missing something

### Edit 1
Few more hours of trying to get it to work with the following outcome
The agent is not forwarded on every execution. I did notice something interesting. When the execution is working the size of the copy of the rsa_key in `/tmp/rundeck` is different from the one on a bad execution when the agent was not forwarded.

good: 
```
# ls -la /tmp/rundeck/
total 136
drwxrwxr-x  2 rundeck rundeck 106496 Mar 18 17:22 .
drwxrwxrwt 16 root    root     20480 Mar 18 17:22 ..
-rw-------  1 rundeck rundeck   1700 Mar 18 17:22 ansible-runner12914193267062717id_rsa
-rw-rw-r--  1 rundeck rundeck    161 Mar 18 17:22 ansible-runner173787406658929431extra-vars
-rw-rw-r--  1 rundeck rundeck      0 Mar 17 15:34 .ehcache-diskstore.lock
```
Not good:
```
# ls -la /tmp/rundeck/
total 140
drwxrwxr-x  3 rundeck rundeck 106496 Mar 18 17:18 .
drwxrwxrwt 16 root    root     20480 Mar 18 17:19 ..
drwx------  2 rundeck rundeck   4096 Mar 18 17:18 ansible-hosts7791614368897163532
-rw-------  1 rundeck rundeck   1675 Mar 18 17:18 ansible-runner4269002367524877318id_rsa
-rw-rw-r--  1 rundeck rundeck     67 Mar 18 17:18 ansible-runner4394417051588116768extra-vars
-rw-rw-r--  1 rundeck rundeck      0 Mar 17 15:34 .ehcache-diskstore.lock
```
More interesting is that the size of the original key is the same as the one in the bad execution.

**Comment by via-justa** [comment]
After a bit more investigation I got to realize 2 points:
a. The agent cleaning is slow so if another execution is starting before the agent was cleaned the use of the agent will fail. After understanding that point I had a restriction and got to issue number 2.
2. I'm using the git module and he's not using the agent. running git clone as sell command does work.

**Comment by mcassaniti** [comment]
The `extra-vars` is also different in size. Are you able to provide feedback on what the difference is for both files? It sounds just plain strange, but isn't that where software bugs start their life?

**Comment by via-justa** [comment]
Hey @mcassaniti I'm no longer sure that's the source of the issue as now I had a job that failed with the file sizing 1700. just for the sake of the argument, the diff between the files is newline at end of file.

I'll need to stop investigating it for now as I spent the major part of 2 days on it. I'll just find a workaround until I got time to continue investigating or you find the source of the issue and release a new version.
If you like to try and reproduce the same steps I'm doing please:
1. Add ssh key to rundeck storage
2. create a job with the following configuration (edit everything marked with `<>`)
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: ops
  loglevel: DEBUG
  name: debug ssh-agent
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: <node>
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-base-dir-path: /var/rundeck/projects/<project>/ansible_playbooks
        ansible-become: 'false'
        ansible-playbook-inline: |-
          - hosts: all
            tasks:
            #- pause:
            #    minutes: 1
            - name: Clone repo
              git:
                repo: 'git@github.com:<org>/<repo>.git'
                dest: "<dest>"
                accept_hostkey: yes
                force: yes
                version: "<version>"
                recursive: no
        ansible-ssh-auth-type: privateKey
        ansible-ssh-key-storage-path: keys/<key>
        ansible-ssh-passphrase-option: option.password
        ansible-ssh-use-agent: 'true'
        ansible-ssh-user: root
      nodeStep: true
      type: com.batix.rundeck.plugins.AnsiblePlaybookInlineWorkflowNodeStep
    keepgoing: false
    strategy: node-first
```
3. Make sure no ssh key is installed on the node.
4. Run the job twice one after the other. (sometimes it fails at the first time but it's failing 100% of the second)
