### ISSUE TITLE
[Q] Custom attributes from fact

### ISSUE THREAD

**Issue by FL3SH** [rundeck-plugins/ansible-plugin#273]
Hello, 
Is it possible to use ansible fact as a custom attribute? I would like to see my attribute (fact_download_speed_in_bytes_per_second) in the node overview.

```yaml
  - name: Set persistent fact
    set_fact:
      fact_download_speed_in_bytes_per_second: download_speed
```
