### ISSUE TITLE
Struggling with "skipping: no hosts matched"

### ISSUE THREAD

**Issue by Nizla** [rundeck-plugins/ansible-plugin#32]
Hi there,

I started using Rundeck and Ansible for a few days from today, and, i've run into a lot of problem, but this one i'm not passing through.
I'm just trying to launch 2 simple playbook into a Cisco Switch who create an ACL Test, and destroy it. Just to test if playbook can work normally.

Playbooks work fine when:
- Launch them from command line as root 
  `ansible-playbook /etc/ansible/playbooks/ios/ios-test-acl.yml`
- Launch them from command line as rundeck
  `su rundeck -s /bin/bash -c "ansible-playbook /etc/ansible/playbooks/ios/ios-test-acl.yml`
- Launch them from Rundeck without the plugin (as Command Line)
  ![success-without](https://cloud.githubusercontent.com/assets/20063277/16228460/8634c3be-37b7-11e6-8f81-e52d9e15cd09.png)

But they won't work when i launch them from Rundeck with the option coming from the plugin (to launch playbook)

![failure-with](https://cloud.githubusercontent.com/assets/20063277/16228762/3c02b704-37b9-11e6-884b-fa63f3e81aae.png)

I'm pretty sure i'm missing something but i can't find what it is and it's pretty frustrating. Here what i've done at the moment.

Project configuration following the readme:

```
#Project Project_Ansible_Plugin configuration, generated
#Tue Jun 21 10:17:13 CEST 2016
project.name=Project_Ansible_Plugin
project.ssh-authentication=privateKey
service.NodeExecutor.default.provider=com.batix.rundeck.AnsibleNodeExecutor
resources.source.1.config.gatherFacts=false
resources.source.1.config.extraArgs=-u root
project.nodeCache.enabled=true
project.ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
project.nodeCache.delay=30
project.description=Project using functionalities from the ansible plugin for rundeck
service.FileCopier.default.provider=com.batix.rundeck.AnsibleFileCopier
executable=/bin/bash
resources.source.1.type=com.batix.rundeck.AnsibleResourceModelSourceFactory
```

ownership from rundeck to /var/lib/rundeck:
`drwxr-xr-x 12 rundeck  root     4.0K Jun 20 16:59 rundeck`

The test command is good:
![pingtest](https://cloud.githubusercontent.com/assets/20063277/16229944/694e7616-37bf-11e6-84a3-07bba08cda70.png)

ansible config file:

```
[defaults]
log_path        = /var/log/ansible.log
inventory       = /etc/ansible/hosts
local_tmp       = $HOME/.ansible/tmp
#host_key_checking  = false

```

node rundeck can see:
![nodes-from-rund](https://cloud.githubusercontent.com/assets/20063277/16230204/960759c4-37c0-11e6-8477-493f7b0470b2.png)

And the host file (with the password which is visible and not crypted for the ssh pass missing here):

```
[localhost]
rundeck ansible_connection=local ansible_host=127.0.0.1 ansible_user=root ansible_ssh_pass=<>
[nxos]
sdc9-n6k-01 ansible_connection=local
[ios]
172.30.253.30 ansible_connection=local
```

Tanks in advance !

Server:
Debian 8.4
Rundeck 2.6.7-1
Ansible 2.1.0.0
Plugin 1.2.4
Java 1.7.0_101
Python 2.7.9
Client:
Cisco IOS - C2960X - 15.0(2)EX5

**Comment by frozenice** [comment]
Wow, thanks for the detailed report! That's a developer's dream. ;)

It seems your playbook targets "172.30.253.30" with its `hosts` entry. But the job screenshot shows Rundeck is trying to run it on node "rundeck".

How did you configure your job? Can you post your job definition as YAML?

**Comment by Nizla** [comment]
That's the behaviour i expect from the playbook. What the playbook try to do is to connect, from the rundeck server, to the switch (172.30.253.30) using SSH. So the playbook must be run locally.

Here the job definition from the job using the plugin:

```
- description: test job which create acl, and destro them afterward
  executionEnabled: true
  id: b80b0aa3-bd1a-48b2-8efe-6842980b6986
  loglevel: INFO
  name: test_acl
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        extraArgs: -u root
        playbook: /etc/ansible/playbooks/ios/ios-test-acl.yml
      description: test the creation of the acl
      nodeStep: true
      type: com.batix.rundeck.AnsiblePlaybookNodeStep
    - configuration:
        extraArgs: -u root
        playbook: /etc/ansible/playbooks/ios/ios-delete-test-acl.yml
      description: test the destruction of the freshly created acl
      nodeStep: true
      type: com.batix.rundeck.AnsiblePlaybookNodeStep
    keepgoing: false
    strategy: node-first
  uuid: b80b0aa3-bd1a-48b2-8efe-6842980b6986
```

Here the job definition from the job who don't:

```
- description: |-
    Test acl creation with ansible module (ios_config)
    and delete them afterward (with ios_config too)
  executionEnabled: true
  id: a97c4e76-ca7c-428a-991d-3f8f5e98b3a5
  loglevel: INFO
  name: test_ansible_acl
  scheduleEnabled: true
  sequence:
    commands:
    - description: create the acl
      exec: ansible-playbook /etc/ansible/playbooks/ios/ios-test-acl.yml
    - description: delete them
      exec: ansible-playbook /etc/ansible/playbooks/ios/ios-delete-test-acl.yml
    keepgoing: false
    strategy: node-first
  uuid: a97c4e76-ca7c-428a-991d-3f8f5e98b3a5
```

And the playbooks i'm using in the job are like these (the module i used are nxos_command and nxos_config).

```
- hosts: ios
  gather_facts: no
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

- name: CREATE 'TEST' ACCESS-LIST
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - 10 permit ip host 1.1.1.1 any
        - 20 deny ip any any
      parents: ['ip access-list extended TEST']
      #before: ['no ip access-list extended TEST']
      match: exact
```

Only put the one for the creation of acl list, the destruction is just the same with 'no ip access-list extended TEST' in lines:
