### ISSUE TITLE
Rundeck 5.2 Ansible. How to disable -l (--limit) option?

### ISSUE THREAD

**Issue by alexsalex** [rundeck-plugins/ansible-plugin#372]
Have a playbook with multiple hosts, hosts generated automatically.

How to disable -l option in Rundeck 5.2?

**Comment by tanji** [comment]
You can't disable limit option in rundeck plugin; limit is always generated from supplied host filter, or you can override it in extra arguments. If you have multiple hosts, why not use ansible group?
Or otherwise, just use inline playbook.

**Comment by alexsalex** [comment]
Use case:
I create a VM in VMware. To do that I use localhost. But I need to add the record in the DHCP server, log in to the server, and change the config. In this case, which arguments and groups should I use? Please, help.

**Comment by wouter-evolane** [comment]
use case:
Provision a host with a cloud provider add it dynamically to the inventory  an run commands on it

This flag breaks the use of [add_host](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html) module. The only workaround is to create a script and call the playbook command instead 
Inline script is not acceptable, the provision process is very long and under git version control

Can also be reproduced locally (the provisioning commands are omitted and localhost is used)

```
- name: Install new node
  gather_facts: false
  any_errors_fatal: true
  hosts: localhost
  tasks:
      - add_host:
          name: "test"
          groups: new
          ansible_host: 127.0.0.1
- name: deploy on installed host
  hosts: new
  gather_facts: false
  vars:
    - ansible_ssh_user: root
    - ansible_ssh_pass: passgoeshere
  tasks:
    - ping:
```
